{{- if and .Values.monitoring.enabled .Values.monitoring.discoveryObjectsEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: terway-cilium
  namespace: {{ .Release.Namespace }}
  annotations:
    arms.prometheus.io/discovery: {{ .Values.monitoring.discoveryAnnotation | quote }}
  labels:
    {{- include "higress-ack-ops.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.monitoring.terway.namespace }}
  selector:
    matchLabels:
      {{- toYaml .Values.monitoring.terway.selector | nindent 6 }}
  podMetricsEndpoints:
    - targetPort: {{ .Values.monitoring.terway.targetPort }}
      path: {{ .Values.monitoring.terway.path }}
      interval: {{ .Values.monitoring.interval }}
      metricRelabelings:
        - sourceLabels: [__name__]
          action: keep
          regex: '^(cilium_bpf_map_pressure|cilium_bpf_map_capacity|cilium_bpf_map_ops_total|cilium_bpf_maps_virtual_memory_max_bytes)$'
{{- end }}
